import type { Metadata } from "next";
import "./globals.css";

const TITLE = "rok0 · Roko Perisic — Solana · Web3 Developer";
const DESCRIPTION =
  "Rust developer from Split, Croatia working at the bottom of the Solana stack. Raw sBPF assembly programs, DeFi primitives, and full-stack web3 products. Currently at Solbound.dev.";
const SITE_URL = "https://rok0.dev"; // update when you have a domain

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: TITLE,
  description: DESCRIPTION,
  keywords: [
    "Solana",
    "sBPF",
    "Rust",
    "Web3",
    "DeFi",
    "smart contracts",
    "Pinocchio",
    "Anchor",
    "assembly",
    "blockchain developer",
    "Roko Perisic",
    "rok0",
    "Solbound",
  ],
  authors: [{ name: "Roko Perisic", url: "https://github.com/rokoperki" }],
  creator: "Roko Perisic",

  openGraph: {
    type: "website",
    url: SITE_URL,
    title: TITLE,
    description: DESCRIPTION,
    siteName: "rok0 // MONITORING TERMINAL",
    locale: "en_US",
    // og image auto-generated by app/opengraph-image.tsx
  },

  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
    creator: "@rok0_sol",
    // og image auto-generated by app/opengraph-image.tsx
  },

  robots: {
    index: true,
    follow: true,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Saira+Condensed:wght@400;500;600;700;800;900&family=JetBrains+Mono:wght@400;500;700&family=VT323&family=Pixelify+Sans:wght@400;500;600;700&family=DotGothic16&family=Noto+Sans+JP:wght@500;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body data-mview="main">{children}</body>
    </html>
  );
}
