import type { Config } from "./types";

export const CONFIG: Config = {
  name: "Roko Perisic",
  handle: "@rok0",
  role: "Solana · Web3 developer",

  about:
    "Systems engineer operating out of Split, Croatia. I work at the instruction level — raw sBPF assembly when compute units are the constraint, Pinocchio and Anchor when they aren't. The machine doesn't lie: binary size, CU consumption, and account layout tell you exactly how well a program is written.\nWhen the protocol needs a face I build that too. APIs, frontends, databases — whatever bridges the on-chain logic to the people using it. I don't stop at the program boundary.\n\nCurrently Rust dev at Solbound.dev. Always building.",

  aboutMeta: [
    { k: "Class", v: "Systems / Protocol" },
    { k: "Base", v: "[Split, Croatia]" },
    { k: "Uptime", v: "3y 201d" },
    { k: "Clearance", v: "OVERSEER" },
  ],

  projects: [
    {
      name: "sBPF TOKEN PROGRAM",
      pid: "0x5BF2",
      mem: "3 KB",
      status: "RUNNING",
      desc: "SPL-compatible token program in raw sBPF assembly — 40× lower CU than SPL Token",
      stack: ["sBPF", "ASSEMBLY", "RUST"],
      role: "AUTHOR",
      year: "2026",
      cpu: 92,
      memPct: 8,
      demo: "https://github.com/rokoperki/sbpf_token_program",
      repo: "https://github.com/rokoperki/sbpf_token_program",
      notes: [
        "transfer costs 118 CU — SPL Token uses 4,736 CU; 40× reduction with zero framework",
        "3 KB binary vs 200 KB+ Anchor equivalent; seven instructions: init, mint, burn, transfer, freeze, thaw, close",
        "outcome: proves sBPF assembly is viable for production token logic at minimal compute cost",
      ],
    },
    {
      name: "ASSEMBLY ESCROW",
      pid: "0xA5C0",
      mem: "6.4 KB",
      status: "RUNNING",
      desc: "Atomic two-party token swap escrow written entirely in raw sBPF assembly",
      stack: ["sBPF", "ASSEMBLY", "SOLANA"],
      role: "AUTHOR",
      year: "2026",
      cpu: 78,
      memPct: 14,
      demo: "https://github.com/rokoperki/assembly_escrow",
      repo: "https://github.com/rokoperki/assembly_escrow",
      notes: [
        "691 instructions, 6,584 bytes — CPI account metadata structs built directly on the stack",
        "PDA vault keyed from maker pubkey + nonce; supports concurrent escrows without account collisions",
        "outcome: atomic make / take / cancel with all instructions under 1% of the 1.4M CU budget",
      ],
    },
    {
      name: "sBPF DISASSEMBLER",
      pid: "0xD1A5",
      mem: "847 KB",
      status: "RUNNING",
      desc: "CLI that fetches any deployed Solana program and outputs annotated sBPF assembly",
      stack: ["RUST", "sBPF", "ELF"],
      role: "AUTHOR",
      year: "2026",
      cpu: 58,
      memPct: 34,
      demo: "https://github.com/rokoperki/sbpf_disassembler",
      repo: "https://github.com/rokoperki/sbpf_disassembler",
      notes: [
        "decodes all sBPF opcode classes — ALU, JMP, loads/stores, calls — with byte offsets and raw encoding",
        "resolves 45+ Murmur3 syscall hashes to human-readable names; reports CU cost per instruction",
        "outcome: inspect any live Solana program from mainnet RPC or a local ELF; JSON output for tooling",
      ],
    },
    {
      name: "LIQUID STAKING TOKEN",
      pid: "0x157A",
      mem: "128 KB",
      status: "RUNNING",
      desc: "Solana program: deposit SOL, receive LST that auto-accrues validator staking rewards",
      stack: ["RUST", "SOLANA", "SPL"],
      role: "AUTHOR",
      year: "2026",
      cpu: 62,
      memPct: 42,
      demo: "https://github.com/rokoperki/liquid-staking-token",
      repo: "https://github.com/rokoperki/liquid-staking-token",
      notes: [
        "PDA-controlled stake accounts; LST value increases over time as validator earns rewards",
        "permissionless reserve management — anyone can crank the rebase, all math is on-chain",
        "outcome: full deposit / withdraw / stake lifecycle in a single native Solana program",
      ],
    },
    {
      name: "MYSTERY PACK TOKEN",
      pid: "0xF4C0",
      mem: "96 KB",
      status: "RUNNING",
      desc: "Randomised NFT mystery pack distribution with Merkle commitment + Switchboard VRF",
      stack: ["RUST", "ANCHOR", "SWITCHBOARD"],
      role: "AUTHOR",
      year: "2026",
      cpu: 48,
      memPct: 56,
      demo: "https://github.com/rokoperki/mystery-pack-token",
      repo: "https://github.com/rokoperki/mystery-pack-token",
      notes: [
        "Merkle tree commits pack contents on-chain before reveal — prevents backend manipulation",
        "Switchboard oracle provides verifiable random function; pack assignment is unbiased and auditable",
        "outcome: fair mystery pack protocol with full client — token program, API, and TypeScript SDK",
      ],
    },
    {
      name: "STARTUP VILLAGE",
      pid: "0x5491",
      mem: "4.2 MB",
      status: "RUNNING",
      desc: "Landing page for a startup accelerator / village program",
      stack: ["NEXT.JS", "TYPESCRIPT", "TAILWIND"],
      role: "LEAD",
      year: "2025",
      cpu: 34,
      memPct: 68,
      demo: "https://startup-village-split.fun/",
      repo: "https://github.com/rokoperki",
      notes: [
        "marketing site for a startup village — programme overview, cohort listings, application flow",
        "built with Next.js App Router; responsive across mobile, tablet, and desktop",
        "outcome: live production site serving programme applications and community information",
      ],
    },
    {
      name: "SOLANA ID",
      pid: "0x501D",
      mem: "2.4 MB",
      status: "RUNNING",
      desc: "Wallet identity & reputation platform — on-chain SOLID Score for Solana addresses",
      stack: ["TYPESCRIPT", "NEST.JS", "NEXT.JS"],
      role: "CONTRIBUTOR",
      year: "2025",
      cpu: 52,
      memPct: 46,
      demo: "https://www.solana.id/",
      repo: "https://github.com/SolanaID",
      notes: [
        "turns a Solana wallet into a super account — attaches reputation score derived from on-chain activity",
        "backend API surfaces SOLID Score, badges, and tier classification for any address via REST",
        "outcome: identity layer used by applications to assess wallet trustworthiness without centralized KYC",
      ],
    },
    {
      name: "BONKZ.IO",
      pid: "0xB04C",
      mem: "3.1 MB",
      status: "RUNNING",
      desc: "Solana NFT ecosystem — 93 1/1 artworks, 90s arcade game, social content channels",
      stack: ["REACT", "NEXT.JS", "SOLANA"],
      role: "LEAD",
      year: "2024",
      cpu: 38,
      memPct: 64,
      demo: "https://bonkz.io",
      repo: "https://bonkz.io",
      notes: [
        "93 unique 1/1 NFT artworks by independent Solana artists; free + paid-to-play arcade game mode",
        "multi-channel content platform — social media, gaming leaderboard, and merchandise storefront",
        "outcome: full NFT ecosystem built on Solana with live web presence and active community",
      ],
    },
  ],

  contact: {
    email: "roko@solbound.dev",
    github: "https://github.com/rokoperki",
    x: "https://x.com/rok0_sol",
    discord: "rokoperki",
  },

  unitLabel: "UNIT 01",

  unitParts: [
    { name: "sBPF ASSEMBLY", status: "OPERATING" },
    { name: "RUST / PINOCCHIO", status: "OPERATING" },
    { name: "SOLANA / ANCHOR", status: "OPERATING" },
    { name: "REACT / NEXT.JS", status: "OPERATING" },
    { name: "TYPESCRIPT / JS", status: "OPERATING" },
    { name: "NEST.JS / NODE", status: "OPERATING" },
    { name: ".NET / C#", status: "SYNC 74%" },
    { name: "POSTGRESQL / PRISMA", status: "OPERATING" },
    { name: "TAILWIND / SCSS", status: "OPERATING" },
    { name: "DOCKER / REST", status: "OPERATING" },
    { name: "SECURITY / AUDIT", status: "SYNC 82%" },
    { name: "ML / AI", status: "DORMANT" },
  ],

  unitChecks: [
    "RUST TOOLCHAIN",
    "SOLANA CLI",
    "NODE / PNPM",
    "DOCKER",
    "POSTGRESQL",
    "GH ACTIONS",
  ],

  unitTags: [
    { k: "AVAILABILITY", v: "Rust dev @ Solbound.dev" },
    { k: "TIMEZONE", v: "UTC+01 · CET" },
    { k: "HARMONICS", v: "STABLE" },
  ],

  bioLayers: [
    {
      id: "001",
      name: "sBPF LAYER",
      sub: "ASSEMBLY · ELF · OPCODES",
      status: "OPERATING",
    },
    {
      id: "002",
      name: "BLOCKCHAIN",
      sub: "RUST · PINOCCHIO · ANCHOR · SPL",
      status: "OPERATING",
    },
    {
      id: "003",
      name: "CLIENT",
      sub: "REACT · NEXT.JS · TAILWIND · SCSS",
      status: "OPERATING",
    },
    {
      id: "004",
      name: "LANGUAGE",
      sub: "TYPESCRIPT · JAVASCRIPT · RUST",
      status: "OPERATING",
    },
    {
      id: "005",
      name: "BACKEND",
      sub: "NEST.JS · NODE.JS · .NET",
      status: "OPERATING",
    },
    {
      id: "006",
      name: "DATABASE",
      sub: "POSTGRESQL · PRISMA · SQL",
      status: "OPERATING",
    },
    {
      id: "007",
      name: "DEVOPS",
      sub: "GIT · DOCKER · REST APIs",
      status: "SYNC 84%",
    },
  ],

  casper: "CASPER",

  classified: {
    directLine: "telegram · @rokoperk1",
    resumeUrl: "/Roko_Perisic_CV.pdf",
    resumeName: "DOWNLOAD CLASSIFIED FILE ▸",
    note: "Wallet auth filters out most of the noise. If you're here with a real reason — a build, a protocol question, a role worth discussing — reach out on Telegram. Not a broadcast inbox.",
  },
};
